### ISSUE TITLE
AttributeError: Can't get attribute 'worker_partial' on <module '__mp_main__'

### ISSUE THREAD

**Issue by NonlinearNimesh** [MIPT-Oulu/KneeLocalizer#5]
Hi, I am getting this below error while running detector.py
In the Data folder i have my dicom files

(base) C:\Users\Nimesh\AnacondaProjects\DeepKnee\KneeLocalizer\oulukneeloc>python detector.py --path_input C:/Users/Nimesh/AnacondaProjects/DeepKnee/ouludeepknee/Data
```
Process SpawnPoolWorker-2:
Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "C:\Users\Nimesh\Anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "C:\Users\Nimesh\Anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Nimesh\Anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Nimesh\Anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Nimesh\Anaconda3\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\Nimesh\Anaconda3\lib\multiprocessing\queues.py", line 368, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\Nimesh\Anaconda3\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\Nimesh\Anaconda3\lib\multiprocessing\queues.py", line 368, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'worker_partial' on <module '__mp_main__' from 'C:\\Users\\Nimesh\\AnacondaProjects\\DeepKnee\\KneeLocalizer\\oulukneeloc\\detector.py'>
```

**Comment by soupault** [comment]
@NonlinearNimesh without getting into the code, this is likely caused by the differences in the implementation of Python multiprocessing between Linux and Windows - https://rhodesmill.org/brandon/2010/python-multiprocessing-linux-windows/ . The DeepKnee and KneeLocalizer codes were developed and tested primarily in Linux. The easiest solution for you would be to run the code in a Linux environment, e.g. inside Ubuntu Docker container.

**Comment by NonlinearNimesh** [comment]
Thanks, Done

**Comment by NonlinearNimesh** [comment]
Hey, Now Stuck Here, can you please see this
```
  File "predict.py", line 80, in <module>
    tmp = load_model(snp_name, KneeNet(args.bw, 0.2, True))
  File "predict.py", line 30, in load_model
    state_dict = torch.load(filename, map_location='cpu')
  File "C:\Users\Nimesh\Anaconda3\envs\deep_knee\lib\site-packages\torch\serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Nimesh\Anaconda3\envs\deep_knee\lib\site-packages\torch\serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.
```

**Comment by NonlinearNimesh** [comment]
Solved, the model was partially downloaded
